apiVersion: v1
kind: ConfigMap
metadata:
  name: server-kubernetes
data:
  spring.datasource.url: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXM6NTQzMi9iYWxhbmNl
  spring.datasource.username: c29tZXVzZXI=
  spring.datasource.password: c29tZXBhc3M=