spring:
  jpa:
    properties:
      hibernate.show_sql: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      hibernate.cache.hazelcast.instance_name: ${spring.application.name}
      hibernate.cache.hazelcast.use_native_client: true
      hibernate.cache.hazelcast.network.kubernetes.service_name: ${HZ_HAZELCAST}